name: Deploy static content to Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

# Only grant the necessary permissions
permissions:
  contents: write # Required for peaceiris/actions-gh-pages to push to gh-pages branch

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
          force_orphan: true
